version: '3.0'

services:
    weather_bot:
        build: app/
        ports:
            - '5000:5000'

        env_file: app/.env
        links:
            - mongo

    mongo:
        image: mongo
        ports:
            - '27017:27017'

    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - weather_bot
