version: '3.0'

services:
    weather_bot:
        build: app/
        env_file:
            - app/.env
        ports:
            - '5000:5000'
        depends_on:
            - mongo
        networks:
            - frontend
            - backend

    mongo:
        build: .
        env_file:
          - app/.env
        restart: always
        networks:
            - backend

    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - weather_bot
        networks:
            - backend
            - frontend

networks:
    frontend:
    backend:
