version: '3.0'

services:
    weather_bot:
        build: app/
        env_file:
            - app/.env
        ports:
            - '5000:5000'
        links:
            - mongo

    mongo:
        build: .
        env_file:
          - app/.env
        restart: always

    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - weather_bot
