version: '3.0'
volumes:
    mongodb_volume:


services:
    weather_bot:
        build: app/
        ports:
            - 5000:5000
        depends_on:
            - mongo
        env_file: app/.env

    mongo:
        image: mongo:5.0.5-focal
        volumes:
            - mongodb_volume:/data/db
        env_file: app/.env

        ports:
            - 27017:27017

    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - weather_bot
