version: '3.0'

services:
    weather_bot:
        build: app/
        ports:
            - '5000:5000'

        env_file: app/.env
        links:
            - mongo

    mongo:
        image: mongo
        volumes:
        - ./mongo-volume:/data/db
        command: mongorestore -d weather_db app/weather_db

    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - weather_bot
