version: '3.0'
volumes:
    mongodb_volume:


services:
    weather_bot:
        build: app/
        ports:
            - 5000:5000
        links:
            - mongodb
        env_file: app/.env

    mongodb:
        image: mongo:5.0.5-focal
        volumes:
            - mongodb_volume:/data/db
        env_file: app/.env


    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - weather_bot
