version: '3.0'
volumes:
    mongodb_volume:


services:
    weather_bot:
        build: app/
        ports:
            - 5000:5000
        links:
            - mongo
        env_file: app/.env

        command: python3 weather_models.py

    mongo:
        image: mongo:5.0.5-focal
        hostname: mongo
        volumes:
            - mongodb_volume:/data/db
        env_file: app/.env



        ports:
            - 27018:27017

    nginx:
        image: nginx
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - weather_bot
